services:
  - type: web
    name: rag-azure-educacional
    env: python
    buildCommand: export CARGO_HOME=/tmp/cargo && pip install --upgrade pip && pip install --prefer-binary --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ENDPOINT
        sync: false
      - key: API_KEY
        sync: false
      - key: API_VERSION
        value: "2024-02-15-preview"
      - key: MODELO
        sync: false
